name: Run the tests, build the image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package


      - name: Build and push the image
        run: |
          docker login --username idilwor --password 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 ghcr.io
          docker build -t ghcr.io/idilwor/coffee-order:latest --file Dockerfile .  
          docker push ghcr.io/idilwor/coffee-order:latest 
